name: dependencies
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^6.0.0
  flutter_bloc: ^6.1.3
  bloc: ^6.1.3
  flutter_share_me: ^0.9.2
  rxdart: ^0.25.0
  equatable: ^2.0.0
  dartz: ^0.9.2
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  formz: ^0.3.2
  cached_network_image: ^2.5.0
  url_launcher: ^6.0.2
  firebase_remote_config: ^0.6.0
  carousel_slider: ^3.0.0
  pinch_zoom: ^0.0.4
  uuid: ^2.2.2
  #firebase
  cloud_firestore: ^0.16.0+1
  firebase_core: ^0.7.0
  # firebase_remote_config: ^0.6.0
  http_interceptor: ^0.3.3
  html_unescape: ^1.0.2
  shimmer: ^1.1.2
  # flutter_screenutil: ^4.0.3+2
  firebase_auth: ^0.20.1
  viewport: ^0.2.0
  # google_sign_in: ^4.5.8
  audioplayers: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
