name: shared
description: A new Flutter package.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # This is our modular
  components:
    path: ../components
  core:
    path: ../core

  #general-plugins
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  flutter_share_me: ^1.3.0
  rxdart: ^0.27.3
  equatable: ^2.0.0
  dartz: ^0.10.1
  http: ^0.13.4
  shared_preferences: ^2.0.13
  formz: ^0.4.1
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.2
  firebase_remote_config: ^2.0.4
  carousel_slider: ^4.0.0
  pinch_zoom: ^1.0.0
  uuid: ^3.0.6
  #firebase
  cloud_firestore: ^3.1.12
  firebase_core: ^1.14.1
  # firebase_remote_config: ^0.6.0
  http_interceptor: ^1.0.2
  html_unescape: ^2.0.0
  shimmer: ^2.0.0
  # flutter_screenutil: ^4.0.3+2
  firebase_auth: ^3.3.14
  viewport: ^0.2.0
  # google_sign_in: ^4.5.8
  audioplayers: ^0.20.1
  auto_route: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  build_runner: ^2.1.7  
  auto_route_generator: ^3.2.1 

flutter: